INSERT INTO FBD.ESTADO
(CO_UF, SG_UF)
SELECT
	ME."CO_UF_ESC",
	ME."SG_UF_ESC"
FROM
	PUBLIC."MICRODADOS_ENEM" ME
WHERE ME."CO_UF_ESC" IS NOT NULL AND ME."SG_UF_ESC" IS NOT NULL
UNION
SELECT
	ME."CO_UF_PROVA"::INT,
	ME."SG_UF_PROVA"
FROM
	PUBLIC."MICRODADOS_ENEM" ME
WHERE ME."CO_UF_PROVA" IS NOT NULL AND ME."SG_UF_PROVA" IS NOT NULL;


INSERT INTO FBD.MUNICIPIO
(CO_UF, CO_MUNICIPIO, NO_MUNICIPIO)
SELECT
	ME."CO_UF_ESC"::INT,
	ME."CO_MUNICIPIO_ESC"::INT,
	ME."NO_MUNICIPIO_ESC"
FROM
	PUBLIC."MICRODADOS_ENEM" ME
WHERE ME."CO_UF_ESC" IS NOT NULL AND
	ME."CO_MUNICIPIO_ESC" IS NOT NULL AND
	ME."NO_MUNICIPIO_ESC" IS NOT NULL 
UNION
SELECT
	ME."CO_UF_PROVA"::INT,
	ME."CO_MUNICIPIO_PROVA"::INT,
	ME."NO_MUNICIPIO_PROVA"
FROM
	PUBLIC."MICRODADOS_ENEM" ME
WHERE ME."CO_UF_PROVA" IS NOT NULL AND
	ME."CO_MUNICIPIO_PROVA" IS NOT NULL AND
	ME."NO_MUNICIPIO_PROVA" IS NOT NULL;

INSERT INTO FBD.ENEM
(CO_ENEM, ANO)
VALUES(NEXTVAL('FBD.ENEM_CO_ENEM_SEQ'::REGCLASS), 2023);


INSERT INTO FBD.ESCOLA (
    TP_DEPENDENCIA_ADM,
    TP_LOCALIZACAO,
    TP_SIT_FUNC,
    TP_ESCOLA,
    TP_ENSINO,
    CO_MUNICIPIO
)
SELECT
    ME."TP_DEPENDENCIA_ADM_ESC"::INT,
    CASE 
         WHEN ME."TP_LOCALIZACAO_ESC"::INT = 1 THEN 'U'
         WHEN ME."TP_LOCALIZACAO_ESC"::INT = 2 THEN 'R'
         ELSE NULL
    END AS TP_LOCALIZACAO,
    ME."TP_SIT_FUNC_ESC"::INT,
    ME."TP_ESCOLA"::INT,
    CASE 
         WHEN ME."TP_ENSINO"::INT = 1 THEN 'R'
         WHEN ME."TP_ENSINO"::INT = 2 THEN 'E'
         ELSE NULL
    END AS TP_ENSINO,
    ME."CO_MUNICIPIO_ESC"::INT
FROM PUBLIC."MICRODADOS_ENEM" ME
GROUP BY 1,2,3,4,5,6;

INSERT INTO FBD.PROVA (
    CO_PROVA_CN,
    CO_PROVA_CH,
    CO_PROVA_LC,
    CO_PROVA_MT,
    TP_LINGUA,
    CO_ENEM
)
SELECT
    "CO_PROVA_CN",
    "CO_PROVA_CH",
    "CO_PROVA_LC",
    "CO_PROVA_MT",
    CASE 
         WHEN "TP_LINGUA" = 0 THEN 'I'
         WHEN "TP_LINGUA" = 1 THEN 'E'
         ELSE NULL
    END AS TP_LINGUA,
    (SELECT CO_ENEM FROM FBD.ENEM WHERE ANO = 2023)
FROM PUBLIC."MICRODADOS_ENEM"
GROUP BY 1,2,3,4,5,6;

INSERT INTO FBD.CANDIDATO (
    NU_INSCRICAO,
    TP_FAIXA_ETARIA,
    TP_SEXO,
    TP_ESTADO_CIVIL,
    TP_COR_RACA,
    TP_NACIONALIDADE,
    IN_TREINEIRO,
    CO_ESCOLA,
    CO_PROVA
)
SELECT
    ME."NU_INSCRICAO",
    ME."TP_FAIXA_ETARIA"::INT,
    ME."TP_SEXO",
    ME."TP_ESTADO_CIVIL"::INT,
    ME."TP_COR_RACA"::INT,
    ME."TP_NACIONALIDADE"::INT,
    CASE 
        WHEN ME."IN_TREINEIRO"::INT = 1 THEN 'S'
        WHEN ME."IN_TREINEIRO"::INT = 0 THEN 'N'
        ELSE NULL
    END,
    ESC.CO_ESCOLA,
    P.CO_PROVA
FROM PUBLIC."MICRODADOS_ENEM" ME
LEFT JOIN FBD.ESCOLA ESC
  ON COALESCE(ESC.TP_DEPENDENCIA_ADM, -1) = COALESCE(ME."TP_DEPENDENCIA_ADM_ESC"::INT, -1)
 AND ESC.TP_LOCALIZACAO IS NOT DISTINCT FROM 
       CASE 
         WHEN ME."TP_LOCALIZACAO_ESC"::INT = 1 THEN 'U'
         WHEN ME."TP_LOCALIZACAO_ESC"::INT = 2 THEN 'R'
         ELSE NULL
       END
 AND COALESCE(ESC.TP_SIT_FUNC, -1) = COALESCE(ME."TP_SIT_FUNC_ESC"::INT, -1)
 AND COALESCE(ESC.TP_ESCOLA, -1) = COALESCE(ME."TP_ESCOLA"::INT, -1)
 AND ESC.TP_ENSINO IS NOT DISTINCT FROM 
       CASE 
         WHEN ME."TP_ENSINO"::INT = 1 THEN 'R'
         WHEN ME."TP_ENSINO"::INT = 2 THEN 'E'
         ELSE NULL
       END
 AND COALESCE(ESC.CO_MUNICIPIO, -1) = COALESCE(ME."CO_MUNICIPIO_ESC"::INT, -1)
LEFT JOIN FBD.PROVA P
  ON COALESCE(P.CO_PROVA_CN, -1) = COALESCE(ME."CO_PROVA_CN"::INT, -1)
 AND COALESCE(P.CO_PROVA_CH, -1) = COALESCE(ME."CO_PROVA_CH"::INT, -1)
 AND COALESCE(P.CO_PROVA_LC, -1) = COALESCE(ME."CO_PROVA_LC"::INT, -1)
 AND COALESCE(P.CO_PROVA_MT, -1) = COALESCE(ME."CO_PROVA_MT"::INT, -1)
 AND P.TP_LINGUA IS NOT DISTINCT FROM 
       CASE 
         WHEN ME."TP_LINGUA"::INT = 0 THEN 'I'
         WHEN ME."TP_LINGUA"::INT = 1 THEN 'E'
         ELSE NULL
       end;

INSERT INTO FBD.HISTORICO_ESCOLAR (TP_ANO_CONCLUIU, TP_SITUACAO_CONCLUSAO, NU_INSCRICAO)
SELECT DISTINCT
    "TP_ANO_CONCLUIU"::INT,
    "TP_ST_CONCLUSAO"::INT,
    "NU_INSCRICAO"
FROM PUBLIC."MICRODADOS_ENEM"
WHERE "TP_ANO_CONCLUIU" IS NOT NULL 
  AND "TP_ST_CONCLUSAO" IS NOT NULL
  AND "NU_INSCRICAO" IS NOT NULL;

INSERT INTO FBD.RESULTADO (
    NU_NOTA_CN,
    NU_NOTA_CH,
    NU_NOTA_LC,
    NU_NOTA_MT,
    NU_NOTA_REDACAO,
    CO_PROVA,
    NU_INSCRICAO
)
SELECT
    ME."NU_NOTA_CN",
    ME."NU_NOTA_CH",
    ME."NU_NOTA_LC",
    ME."NU_NOTA_MT",
    ME."NU_NOTA_REDACAO",
    P.CO_PROVA,
    ME."NU_INSCRICAO"::BIGINT
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PROVA P 
  ON COALESCE(P.CO_PROVA_CN, -1) = COALESCE(ME."CO_PROVA_CN"::INT, -1)
 AND COALESCE(P.CO_PROVA_CH, -1) = COALESCE(ME."CO_PROVA_CH"::INT, -1)
 AND COALESCE(P.CO_PROVA_LC, -1) = COALESCE(ME."CO_PROVA_LC"::INT, -1)
 AND COALESCE(P.CO_PROVA_MT, -1) = COALESCE(ME."CO_PROVA_MT"::INT, -1)
 AND P.TP_LINGUA IS NOT DISTINCT FROM 
       CASE 
         WHEN ME."TP_LINGUA"::INT = 0 THEN 'I'
         WHEN ME."TP_LINGUA"::INT = 1 THEN 'E'
         ELSE NULL
       END;


INSERT INTO FBD.PRESENCA (
    TP_PRESENCA_CN,
    TP_PRESENCA_CH,
    TP_PRESENCA_LC,
    TP_PRESENCA_MT,
    CO_MUNICIPIO,
    NU_INSCRICAO
)
SELECT
    "TP_PRESENCA_CN"::INT,
    "TP_PRESENCA_CH"::INT,
    "TP_PRESENCA_LC"::INT,
    "TP_PRESENCA_MT"::INT,
    "CO_MUNICIPIO_PROVA"::INT,
    "NU_INSCRICAO"
FROM PUBLIC."MICRODADOS_ENEM";

INSERT INTO FBD.REDACAO (
    TP_STATUS_REDACAO,
    NU_NOTA_COMP1,
    NU_NOTA_COMP2,
    NU_NOTA_COMP3,
    NU_NOTA_COMP4,
    NU_NOTA_COMP5,
    NU_NOTA_REDACAO,
    NU_INSCRICAO
)
SELECT
    "TP_STATUS_REDACAO"::INT,
    "NU_NOTA_COMP1"::INT,
    "NU_NOTA_COMP2"::INT,
    "NU_NOTA_COMP3"::INT,
    "NU_NOTA_COMP4"::INT,
    "NU_NOTA_COMP5"::INT,
    "NU_NOTA_REDACAO"::INT,
    "NU_INSCRICAO"
FROM PUBLIC."MICRODADOS_ENEM";



-- QUERY PARA Q001
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 1
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q001"::VARCHAR
WHERE ME."Q001" IS NOT NULL;

-- QUERY PARA Q002
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 2
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q002"::VARCHAR
WHERE ME."Q002" IS NOT NULL;

-- QUERY PARA Q003
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 3
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q003"::VARCHAR
WHERE ME."Q003" IS NOT NULL;

-- QUERY PARA Q004
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 4
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q004"::VARCHAR
WHERE ME."Q004" IS NOT NULL;

-- QUERY PARA Q005
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 5
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q005"::VARCHAR
WHERE ME."Q005" IS NOT NULL;

-- QUERY PARA Q006
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 6
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q006"::VARCHAR
WHERE ME."Q006" IS NOT NULL;

-- QUERY PARA Q007
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 7
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q007"::VARCHAR
WHERE ME."Q007" IS NOT NULL;

-- QUERY PARA Q008
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 8
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q008"::VARCHAR
WHERE ME."Q008" IS NOT NULL;

-- QUERY PARA Q009
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 9
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q009"::VARCHAR
WHERE ME."Q009" IS NOT NULL;

-- QUERY PARA Q010
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 10
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q010"::VARCHAR
WHERE ME."Q010" IS NOT NULL;

-- QUERY PARA Q011
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 11
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q011"::VARCHAR
WHERE ME."Q011" IS NOT NULL;

-- QUERY PARA Q012
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 12
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q012"::VARCHAR
WHERE ME."Q012" IS NOT NULL;

-- QUERY PARA Q013
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 13
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q013"::VARCHAR
WHERE ME."Q013" IS NOT NULL;

-- QUERY PARA Q014
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 14
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q014"::VARCHAR
WHERE ME."Q014" IS NOT NULL;

-- QUERY PARA Q015
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 15
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q015"::VARCHAR
WHERE ME."Q015" IS NOT NULL;

-- QUERY PARA Q016
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 16
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q016"::VARCHAR
WHERE ME."Q016" IS NOT NULL;

-- QUERY PARA Q017
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 17
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q017"::VARCHAR
WHERE ME."Q017" IS NOT NULL;

-- QUERY PARA Q018
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 18
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q018"::VARCHAR
WHERE ME."Q018" IS NOT NULL;

-- QUERY PARA Q019
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 19
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q019"::VARCHAR
WHERE ME."Q019" IS NOT NULL;

-- QUERY PARA Q020
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 20
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q020"::VARCHAR
WHERE ME."Q020" IS NOT NULL;

-- QUERY PARA Q021
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 21
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q021"::VARCHAR
WHERE ME."Q021" IS NOT NULL;

-- QUERY PARA Q022
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 22
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q022"::VARCHAR
WHERE ME."Q022" IS NOT NULL;

-- QUERY PARA Q023
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 23
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q023"::VARCHAR
WHERE ME."Q023" IS NOT NULL;

-- QUERY PARA Q024
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 24
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q024"::VARCHAR
WHERE ME."Q024" IS NOT NULL;

-- QUERY PARA Q025
INSERT INTO FBD.QUESTIONARIO (NU_INSCRICAO, CO_PERGUNTA, CO_RESPOSTA)
SELECT ME."NU_INSCRICAO", P.CO_PERGUNTA, R.CO_RESPOSTA
FROM PUBLIC."MICRODADOS_ENEM" ME
JOIN FBD.PERGUNTAS P ON P.CODIGO = 25
JOIN FBD.RESPOSTAS R ON R.CO_PERGUNTA = P.CO_PERGUNTA AND R.OPCAO = ME."Q025"::VARCHAR
WHERE ME."Q025" IS NOT NULL;