import polars as pl


ITENS_PROVA_SCHEMA = {
    # -- Colunas Numéricas --
    "CO_POSICAO": pl.Int32,  # Tamanho 3 (mas podemos guardar em Int32)
    "CO_ITEM": pl.Int32,  # Tamanho 5
    "CO_HABILIDADE": pl.Int32,  # Tamanho 2
    "IN_ITEM_ABAN": pl.Int8,  # Tamanho 1 (0 ou 1)
    "NU_PARAM_A": pl.Float64,  # Tamanho 9 (pode ser decimal, então Float64)
    "NU_PARAM_B": pl.Float64,  # idem
    "NU_PARAM_C": pl.Float64,  # idem
    "CO_PROVA": pl.Int32,  # Tamanho 3
    "TP_LINGUA": pl.Int8,  # Tamanho 1 (0 ou 1)
    "IN_ITEM_ADAPTADO": pl.Int8,  # Tamanho 1 (0 ou 1)
    # -- Colunas Alfanuméricas --
    "SG_AREA": pl.Utf8,  # 2 caracteres (ex.: CH, CN, LC, MT)
    "TX_GABARITO": pl.Utf8,  # 1 caractere
    "TX_MOTIVO_ABAN": pl.Utf8,  # até 40 caracteres
    "TX_COR": pl.Utf8,  # até 7 caracteres (ex.: "AMARELA")
}

MICRODADOS_ENEM_SCHEMA = {
    # --- Numéricas (geralmente inteiros) ---
    "NU_INSCRICAO": pl.Int64,
    "NU_ANO": pl.Int16,
    "TP_FAIXA_ETARIA": pl.Int16,
    "TP_ESTADO_CIVIL": pl.Int8,
    "TP_COR_RACA": pl.Int8,
    "TP_NACIONALIDADE": pl.Int8,
    "TP_ST_CONCLUSAO": pl.Int8,
    "TP_ANO_CONCLUIU": pl.Int16,
    "TP_ESCOLA": pl.Int8,
    "TP_ENSINO": pl.Int8,
    "IN_TREINEIRO": pl.Int8,
    "CO_MUNICIPIO_ESC": pl.Int32,
    "CO_UF_ESC": pl.Int16,
    "TP_DEPENDENCIA_ADM_ESC": pl.Int8,
    "TP_LOCALIZACAO_ESC": pl.Int8,
    "TP_SIT_FUNC_ESC": pl.Int8,
    "CO_MUNICIPIO_PROVA": pl.Int32,
    # CO_UF_PROVA consta como Alfanumérica abaixo,
    # mas se for numérica, você pode usar pl.Int16 ou pl.Int8
    "TP_PRESENCA_CN": pl.Int8,
    "TP_PRESENCA_CH": pl.Int8,
    "TP_PRESENCA_LC": pl.Int8,
    "TP_PRESENCA_MT": pl.Int8,
    "CO_PROVA_CN": pl.Int32,
    "CO_PROVA_CH": pl.Int32,
    "CO_PROVA_LC": pl.Int32,
    "CO_PROVA_MT": pl.Int32,
    "TP_LINGUA": pl.Int8,
    "TP_STATUS_REDACAO": pl.Int8,
    # Notas (geralmente decimais)
    "NU_NOTA_CN": pl.Float64,
    "NU_NOTA_CH": pl.Float64,
    "NU_NOTA_LC": pl.Float64,
    "NU_NOTA_MT": pl.Float64,
    "NU_NOTA_COMP1": pl.Float64,
    "NU_NOTA_COMP2": pl.Float64,
    "NU_NOTA_COMP3": pl.Float64,
    "NU_NOTA_COMP4": pl.Float64,
    "NU_NOTA_COMP5": pl.Float64,
    "NU_NOTA_REDACAO": pl.Float64,
    # --- Alfanuméricas ---
    "TP_SEXO": pl.Utf8,
    "NO_MUNICIPIO_ESC": pl.Utf8,
    "SG_UF_ESC": pl.Utf8,
    "NO_MUNICIPIO_PROVA": pl.Utf8,
    "CO_UF_PROVA": pl.Utf8,  # segundo o dicionário está Alfanumérica
    "SG_UF_PROVA": pl.Utf8,
    "TX_RESPOSTAS_CN": pl.Utf8,
    "TX_RESPOSTAS_CH": pl.Utf8,
    "TX_RESPOSTAS_LC": pl.Utf8,
    "TX_RESPOSTAS_MT": pl.Utf8,
    "TX_GABARITO_CN": pl.Utf8,
    "TX_GABARITO_CH": pl.Utf8,
    "TX_GABARITO_LC": pl.Utf8,
    "TX_GABARITO_MT": pl.Utf8,
    # Questionário socioeconômico
    "Q001": pl.Utf8,
    "Q002": pl.Utf8,
    "Q003": pl.Utf8,
    "Q004": pl.Int8,
    "Q005": pl.Int8,
    "Q006": pl.Utf8,
    "Q007": pl.Utf8,
    "Q008": pl.Utf8,
    "Q009": pl.Utf8,
    "Q010": pl.Utf8,
    "Q011": pl.Utf8,
    "Q012": pl.Utf8,
    "Q013": pl.Utf8,
    "Q014": pl.Utf8,
    "Q015": pl.Utf8,
    "Q016": pl.Utf8,
    "Q017": pl.Utf8,
    "Q018": pl.Utf8,
    "Q019": pl.Utf8,
    "Q020": pl.Utf8,
    "Q021": pl.Utf8,
    "Q022": pl.Utf8,
    "Q023": pl.Utf8,
    "Q024": pl.Utf8,
    "Q025": pl.Utf8,
}

ITENS_PROVA_MAP = {
    "SG_AREA": {
        "CH": "Ciências Humanas",
        "CN": "Ciências da Natureza",
        "LC": "Linguagens e Códigos",
        "MT": "Matemática",
    },
    "TP_LINGUA": {
        0: "Inglês",
        1: "Espanhol",
    },
    "IN_ITEM_ADAPTADO": {
        1: "Sim",
        0: "Não",
    },
    "IN_ITEM_ABAN": {
        1: "Sim",
        0: "Não",
    },
}

MICRODADOS_ENEM_MAP = {
    "TP_FAIXA_ETARIA": {
        1: "Menor de 17 anos",
        2: "17 anos",
        3: "18 anos",
        4: "19 anos",
        5: "20 anos",
        6: "21 anos",
        7: "22 anos",
        8: "23 anos",
        9: "24 anos",
        10: "25 anos",
        11: "Entre 26 e 30 anos",
        12: "Entre 31 e 35 anos",
        13: "Entre 36 e 40 anos",
        14: "Entre 41 e 45 anos",
        15: "Entre 46 e 50 anos",
        16: "Entre 51 e 55 anos",
        17: "Entre 56 e 60 anos",
        18: "Entre 61 e 65 anos",
        19: "Entre 66 e 70 anos",
        20: "Maior de 70 anos",
    },
    "IN_TREINEIRO": {1: "Sim", 0: "Não"},
    "TP_DEPENDENCIA_ADM_ESC": {
        1: "Federal",
        2: "Estadual",
        3: "Municipal",
        4: "Privada",
    },
    "TP_LOCALIZACAO_ESC": {1: "Urbana", 2: "Rural"},
    "TP_SIT_FUNC_ESC": {
        1: "Em atividade",
        2: "Paralisada",
        3: "Extinta",
        4: "Escola extinta em anos anteriores",
    },
    "TP_SEXO": {"M": "Masculino", "F": "Feminino"},
    "TP_ESTADO_CIVIL": {
        0: "Não informado",
        1: "Solteiro(a)",
        2: "Casado(a)/Mora com um(a) companheiro(a)",
        3: "Divorciado(a)/Desquitado(a)/Separado(a)",
        4: "Viúvo(a)",
    },
    "TP_COR_RACA": {
        0: "Não declarado",
        1: "Branca",
        2: "Preta",
        3: "Parda",
        4: "Amarela",
        5: "Indígena",
        6: "Não dispõe da informação",
    },
    "TP_NACIONALIDADE": {
        0: "Não informado",
        1: "Brasileiro(a)",
        2: "Brasileiro(a) Naturalizado(a)",
        3: "Estrangeiro(a)",
        4: "Brasileiro(a) Nato(a), nascido(a) no exterior",
    },
    "TP_ST_CONCLUSAO": {
        1: "Já concluí o Ensino Médio",
        2: "Estou cursando e concluirei o Ensino Médio em 2023",
        3: "Estou cursando e concluirei o Ensino Médio após 2023",
        4: "Não concluí e não estou cursando o Ensino Médio",
    },
    "TP_ANO_CONCLUIU": {
        0: "Não informado",
        1: "2022",
        2: "2021",
        3: "2020",
        4: "2019",
        5: "2018",
        6: "2017",
        7: "2016",
        8: "2015",
        9: "2014",
        10: "2013",
        11: "2012",
        12: "2011",
        13: "2010",
        14: "2009",
        15: "2008",
        16: "2007",
        17: "Anterior a 2007",
    },
    "TP_ESCOLA": {1: "Não respondeu", 2: "Pública", 3: "Privada"},
    "TP_ENSINO": {
        1: "Ensino Regular",
        2: "Educação Especial - Modalidade Substitutiva",
    },
    "TP_PRESENCA_CN": {
        0: "Faltou à prova",
        1: "Presente na prova",
        2: "Eliminado na prova",
    },
    "TP_PRESENCA_CH": {
        0: "Faltou à prova",
        1: "Presente na prova",
        2: "Eliminado na prova",
    },
    "TP_PRESENCA_LC": {
        0: "Faltou à prova",
        1: "Presente na prova",
        2: "Eliminado na prova",
    },
    "TP_PRESENCA_MT": {
        0: "Faltou à prova",
        1: "Presente na prova",
        2: "Eliminado na prova",
    },
    "TP_LINGUA": {0: "Inglês", 1: "Espanhol"},
    "TP_STATUS_REDACAO": {
        1: "Sem problemas",
        2: "Anulada",
        3: "Cópia Texto Motivador",
        4: "Em Branco",
        5: "Fere Direitos Humanos",
        6: "Fuga ao tema",
        7: "Não atendimento ao tipo",
        8: "Texto insuficiente",
        9: "Parte desconectada",
    },
    "Q001": {
        "A": "Nunca estudou",
        "B": "Não completou a 4ª série/5º ano do ensino fundamental",
        "C": "Completou a 4ª série/5º ano, mas não completou a 8ª série/9º ano do ensino fundamental",
        "D": "Completou a 8ª série/9º ano do ensino fundamental, mas não completou o Ensino Médio",
        "E": "Completou o Ensino Médio, mas não completou a Faculdade",
        "F": "Completou a Faculdade, mas não completou a Pós-graduação",
        "G": "Completou a Pós-graduação",
        "H": "Não sei",
    },
    "Q002": {
        "A": "Nunca estudou",
        "B": "Não completou a 4ª série/5º ano do ensino fundamental",
        "C": "Completou a 4ª série/5º ano, mas não completou a 8ª série/9º ano do ensino fundamental",
        "D": "Completou a 8ª série/9º ano do ensino fundamental, mas não completou o Ensino Médio",
        "E": "Completou o Ensino Médio, mas não completou a Faculdade",
        "F": "Completou a Faculdade, mas não completou a Pós-graduação",
        "G": "Completou a Pós-graduação",
        "H": "Não sei",
    },
    "Q003": {
        "A": "Grupo 1",
        "B": "Grupo 2",
        "C": "Grupo 3",
        "D": "Grupo 4",
        "E": "Grupo 5",
        "F": "Não Sei",
    },
    "Q004": {
        "A": "Grupo 1",
        "B": "Grupo 2",
        "C": "Grupo 3",
        "D": "Grupo 4",
        "E": "Grupo 5",
        "F": "Não Sei",
    },
    "Q005": {i: str(i) for i in range(1, 21)},
    "Q006": {
        "A": "Nenhuma Renda",
        "B": "Até R$ 1.320,00",
        "C": "De R$ 1.320,01 até R$ 1.980,00",
        "D": "De R$ 1.980,01 até R$ 2.640,00",
        "E": "De R$ 2.640,01 até R$ 3.300,00",
        "F": "De R$ 3.300,01 até R$ 3.960,00",
        "G": "De R$ 3.960,01 até R$ 5.280,00",
        "H": "De R$ 5.280,01 até R$ 6.600,00",
        "I": "De R$ 6.600,01 até R$ 7.920,00",
        "J": "De R$ 7.920,01 até R$ 9.240,00",
        "K": "De R$ 9.240,01 até R$ 10.560,00",
        "L": "De R$ 10.560,01 até R$ 11.880,00",
        "M": "De R$ 11.880,01 até R$ 13.200,00",
        "N": "De R$ 13.200,01 até R$ 15.840,00",
        "O": "De R$ 15.840,01 até R$ 19.800,00",
        "P": "De R$ 19.800,01 até R$ 26.400,00",
        "Q": "Acima de R$ 26.400,00",
    },
}
